JOJ0/synadm

- synadm.py
This avoids leaking the access token in HTTP server logs and is explicitly
recommended by the matrix specification.
(depends on #2)
> Use header instead of query param for auth

- README.md
- synadm/api.py
- synadm/cli/user.py
I was testing a Synapse admin web UI (https://github.com/Awesome-Technologies/synapse-admin
) when I found that I could see all the sessions of a user (including the IP address they used when logging in). This cheat-like feature sounds useful, and so I made this PR.
Not sure if I should add "including IP addresses information" in the docstring.
> Implement command for user whois

- README.md
In this web UI (https://github.com/Awesome-Technologies/synapse-admin), in one of the screenshot, there is an option to erase user data (for GDPR). I thought synadm doesn't have this feature yet until I grepped the codebase and found that it exists. This feature should be told to the user at the top level documentation.
> README: Say that `user deactivate` also has GDPR erase option

- synadm/api.py
- synadm/cli/room.py
When you need to get the `room_id` from a known `room_alias` you can now use `room resolve <room_alias>`. This is handy when one also uses other tools besides `synadm` that may only use a `room_id` and cannot operate with a `room_alias`.
Example:
```
synadm room resolve "#foo:matrix.org"
-------  ------------------------------
room_id  !jLHcnCpckBMWIfzTOa:matrix.org
servers  ['matrix.org']
-------  ------------------------------
```
> Implements room_alias resolution to room_id

- synadm/cli/user.py
Activating users in an SSO environment is a valid operation even when not providing a password. We shouldn't require a password to be set in those cases.
> Activating a user without setting a password is a valid user case

- synadm/api.py
This fixes the issue I've described at https://matrix.to/#/!mLATeUxylgHiofUzHJ:peek-a-boo.at/$uxyw6W9u-nepUREGUFnWT2tsJ42hC90uT2B__IvaU3U?via=peek-a-boo.at&via=matrix.org&via=matrix.forster.cc where deleting media with given ID fails with Unrecognized request error.
> Remove trailing slash from media API calls

- .gitignore
- README.md
- synadm/api.py
- synadm/cli/user.py
Hi JOJ0,
I quickly implemented a first appraoch to the shadow-ban command, based on your work. Hopefully this is useful to you.
If have tried to follow your documentation and command style. However, please let me know if my implementation approach does meet your requirements regarding documentation or command structure.
Additionally I added the `env` folder for virtual python environments to the `.gitignore`
> Shadow-ban command

- synadm/cli/user.py
Fixed an issue where the human output of the `shadow-ban` command would not distinguish between '_ban_' and the '_unban_'. Now the human output is adjusted based on the selected option
> Adjusted human output of shadow-ban command

- synadm/cli/__init__.py
When the output consists only of a single value (such as the result of "synadm room resolve"), humanize() returned None, causing nothing at all to be printed.
> cli: fall back to str() instead of silence for human output

- synadm/api.py
- synadm/cli/matrix.py
- synadm/cli/media.py
- synadm/cli/room.py
- synadm/cli/user.py
Users can now enter the localpart as `<user_id>` argument instead of providing the full MXID
> Added support for localpart as <user_id> argument

- synadm/api.py
- If fetching of key/v2/server doesn't get a response at all (api.query
returned None already) fail and log immediately instead of trying to look
into a dict.
- Try to look into the dict in a second step (or).
> Fix NoneType err in server_name method

- requirements.txt
- setup.py
- synadm/api.py
- synadm/cli/__init__.py
- synadm/cli/matrix.py
- synadm/cli/media.py
- synadm/cli/room.py
- synadm/cli/user.py
With regards to #68 this PR aims to change the method of retrieving the server name.
Before the keys/v2/server can be used to retrieve our own servername, it's required to know where the Server-Server aka federation API is located. According to the Matrix spec there is [a definite way to achieving that in the matrix spec
](https://spec.matrix.org/v1.2/server-server-api/#resolving-server-names). It was determined that the admin should be given the freedom to configure the methods (well-known and DNS), rather than implementing an auto-fallback as described in the spec. This should help simplify the implementation and increase performance once set up via synadm config.
As part of this change two new config options `homeserver` and `server_discovery` are utilized.
- `homeserver`: by default …
> Auto-retrieve or use a pre-configured homeserver name

- synadm/cli/__init__.py
wrong variable name in the config subcommand.
> Fix --server-discovery help and a

- README.md
- synadm/api.py
- synadm/cli/__init__.py
- synadm/cli/notice.py
Implemented features (for now):
- Send to single matrix IDs or to all mxids matching a regular expression
- Uses pagination when sending to multiple users (batches of 100 by default, tunable by CLI option)
- Specify notice content in command arguments or in files
- Supports both unformatted and unformatted+formatted message content
- Asks for confirmation (including message content and sample mxids the notice will be sent to) by default before sending - can be disabled by flag
> Add server notice support

- synadm/api.py
- synadm/cli/user.py
This PR adds support for admin endpoint for finding users by their external id on auth provider, which was added in Synapse v1.68.0
Unlike other endpoints, it requires 2 values:
- auth provider id
- external id for the user
> [Documentation for this admin api endpoint](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#find-a-user-based-on-their-id-in-an-auth-provider)
```
$ synadm user auth-provider -p oidc ash
{"user_id": "@ashfame:synapse.dev"}
```
```
$ synadm user auth-provider ash
You must provide a value for provider using --provider
$ synadm user auth-provider
Usage: synadm user auth-provider [OPTIONS] EXTERNAL_ID
Try 'synadm user auth-provider -h' for help.
Error: Missing argument 'EXTERNAL_ID'.
```
Looking forward to your feedback!
Subsequent PR to follow …
> add command auth-provider for finding users by their external id on auth provider

- synadm/api.py
- synadm/cli/user.py
This PR adds support for 3PID endpoint for finding users by their 3PID value which could be an `email` or `msidn` (specified as medium).
Please note this requires Synapse v1.72.0 (I currently haven't been able to test this as our EMS server is still v1.71.0 and would get upgraded hopefully next week but this is relatively straight forward).
Unlike other endpoints but similar to auth-provider endpoint, it requires 2 values:
- medium (`email` or `msidn`)
- address (actual email address or phone number as per medium specified)
> [Documentation for this admin api endpoint](https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#find-a-user-based-on-their-third-party-id-threepid-or-3pid)
```
$ synadm user 3pid -m email universe@github.com
{"user_id": "@ashfame:synapse.dev"} …
```
> add command 3pid for finding user by their 3PID

- synadm/cli/user.py
PR fixes the correct function name to be invoked in 3pid command added in last PR (#81).
Not sure what happened but feels like deja vu. I made this change earlier as well 🤷 
Sorry about this. I have now tested this with Synapse v1.72.0 and it works fine.
> Correction: use the right function

- synadm/api.py
- synadm/cli/media.py
For now by id only, but with option group already. We'd like to streamline with quarantine command later on and add per user ans room options later on.
> Implement media unquarantine command

- synadm/cli/__init__.py
- Keep -o json as the new default as the PR suggests.
- Add a new mode -o jsonmini that still outputs oneline-json as the original json output mode did.
- Improve handling of help text. We didn't have any description of the modes with the global --output flag. It was hidden with the config -o subcommand. It's shown in both places now.
> Finalize PR #84 and improve --output helptext

- setup.py
from setup.py and requirements.txt and add missing wheel package to fix pyyaml bdist_wheel error during pip install.
Fixes #97
> Adapt Click version requirement

- synadm/cli/room.py
it basically duplicates the details command, but now it has error
handling.
this code could probably be better if ctx.invoke returned something
useful instead of None, like info about the request or whatever.
fixes #87
References: https://github.com/JOJ0/synadm/issues/87
> catch missing rooms when deleting

- synadm/api.py
- synadm/cli/user.py
The user_type value is not checked (yet?) the code, although the spec allows only types `bot` and `support` (and the API will respond with `M_UNKNOWN` if an invalid value is sent). If it should be checked, let me know and i will update the PR.
> Make it possible to change user type

- synadm/api.py
- synadm/cli/user.py
Resolves #56
Note: This PR contains more than one change:
- User list pagination
- (Main) Deactivate multiple accounts based on regex (depends on user list pagination)
I don't suggest squashing this.
> User list pagination & Deactivate multiple accounts based on regex

- synadm/cli/__init__.py
- synadm/cli/group.py
- synadm/cli/history.py
- synadm/cli/matrix.py
- synadm/cli/notice.py
- synadm/cli/room.py
- synadm/cli/user.py
- Describe the "mode" in --help as "non-interactive mode"
- Add a new alias for the mode named "--no-confirm"
- Use this name as the variable name throught the project's code.
- Remove the alias "--scripting" of that mode. This might be a breaking change for users that should be discussed before merging.
> Rename from batch mode to non-interactive mode

- synadm/cli/notice.py
- Add it as the first option so the variables in code is now named batch_size and adapt code accordingly.
- Keep paginate as an alternative option.
- Change helptext just slightly.
> Streamline notice send --batch-size option

- synadm/api.py
- synadm/cli/__init__.py
Allow to param ssl_verify in configuration, allow to request https localhost homeserver with self signed certificate.
`~/.config/synadm.yaml`
```
ssl_verify: False
```
Signed-off-by: sebastien.heurtematte <sebastien.heurtematte@eclipse-foundation.org>
> Add ssl_verify to manage selfsigned certificate

- setup.py
due to 63fa8e5d7366ebc73696af8fbe1292538fb3fcf3, it does not work with Click==7.0, only Click==7.1.
I don't know why it doesn't work, but that's for another time to figure out.
i'd suggest we make a release for this?
fixes https://github.com/JOJ0/synadm/issues/106
> bump Click version requirement

- synadm/api.py
1. query now accepts other things as part of str.format
2. refactor all use of the query function in the project
3. function documentation could be much better
4. needs documentation on how to use query function
resolves #96
---
Things to look out for in this PR:
- Nothing should an f-string or already have the information embedded in the URL part (AKA it should be [this](https://github.com/JOJ0/synadm/pull/105/files#diff-21da8274044fdb3c233e057a58a867c3e934030edd102cbe0a79a61858386d20R584) not [this](https://github.com/JOJ0/synadm/pull/105/files#diff-21da8274044fdb3c233e057a58a867c3e934030edd102cbe0a79a61858386d20L564))
- Basically given enough information to get back a string OR `str.format` doesn't break because it wasn't given enough things
> URL encoding in query function and refactor

- CONTRIBUTING.md
This fixes links to code snippets in CONTRIBUTING.md chapter "Implementation Examples" and adds a chapter about the newly introduced way of formatting strings in the `query()` method of `ApiRequest`.
> Fix outdated docs and add "URL encoding chapter"

- .readthedocs.yaml
dev branch seems to build fine now.  I tested by deleting all the configurations from rtd-UI (Admin - Advanced Settings - Default Settings)
master/latest is failing right now but that is expected. It should build fine again after mergen this PR, which I will do without waiting for a review. This is just an informative PR to keep our merge history tidy.
> Migrate readthedocs "config via UI" to .readthedocs.yaml

- synadm/cli/__init__.py
Use isinstance() instead of type() as the current flake8 version suggests.
> Fix type checks in ApiHelper.load()

- doc/source/index_cli_reference.rst
- doc/source/synadm.cli.raw.rst
- synadm/api.py
- synadm/cli/__init__.py
- synadm/cli/_common.py
- synadm/cli/matrix.py
- synadm/cli/raw.py
Addressing 2 things:
- A new subcommand `synadm raw` that should, very similar to what we have in`synadm matrix raw`, be able to rudimentary issue custom requests (that don't have their own synadm commmand yet). Fixes #11
- Finally provide a way to a common problem in the synadm project: Often it's desired to share options or groups of options with multiple commands, even when they are in different "main commands" (live in different modules).
- Introducing a new module `synadm.cli._common` containing such options and option groups.
- The new `raw` command will make use of it.
> Add `raw` command, a new module for common CLI options, and improve `matrix raw` help

- synadm/api.py
- synadm/cli/user.py
Fixes #135
Improve the `--threepid`option of the `user modify` command.
- Support removing **all** threepids by passing `--clear-threepids`
Note: If a user has the idea/follows the logic that resetting according to the API docs (https://matrix-org.github.io/synapse/latest/admin_api/user_admin_api.html#create-or-modify-account) should also work by setting it to "empty", ie. `--threepid '' ''`, that will also work, but it is not documented in `--help`!
- Extend and clarify `--help` for this option.
- Fix an issue where passing multiple `--threepid` options, sets only the last of the argument pairs the user had provided on the cli (ignoring all others).
> User modify command threepid handling fixes

- synadm/__main__.py
As explained previously, I want to add the click generated bash completion script to the Debian package. Here is the change I sent to the Debian maintainer of synadm : https://salsa.debian.org/matrix-team/synadm/-/merge_requests/1
The only way I found to make it work was to add a "main" file that allows to run synadm without installing it. As I thought it could be useful outside the Debian package, here is the forwarded patch, that allows to run synadm directly with `python -m synadm`.
I am no expert in Python so this might not be the ideal way to do it.
> Allow to run the module without installing it

- doc/source/_static/synadm.css
- doc/source/conf.py
- doc/source/features.rst
- rtd_requirements.txt
- sphinx_requirements.txt
> Docs theme change

- README.md
I'd like to include this change to the README as a first step. That way we can further postpone the overhaul in #146
> Point to "API to CLI" docs in README

- CONTRIBUTING.md
- scrape_docs.py
Some changes to make CONTRIBUTING.md and scrape_docs.py more aligned with how it's currently formatted in the actual documentation
> API CLI mapping docs consistency
